version: '3.1'
services:
  app:
    container_name: homies-springboot-postgresql
    image: homies-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    restart: always  
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always  
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres  
