# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Package
      run: mvn -f projSpring/homies_marketplace/pom.xml clean package -DskipTests
    - name: Maven Verify
      run: mvn -f projSpring/homies_marketplace/pom.xml clean verify
    
    - uses: actions/checkout@v2
    - name: Execute app
      run: mvn -f projSpring/homies_marketplace/pom.xml spring-boot:run
