# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CD:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven package
      run: mvn -f projSpring/homies_marketplace/pom.xml clean package -DskipTests
    - name: Maven verify 
      run: mvn -f projSpring/homies_marketplace/pom.xml clean verify
    - name: CD Pipeline
      run: docker-compose -d -f projSpring/homies_marketplace/docker-compose.yml up --build
     
        
